BHoM/Test_Toolkit

.gitattributes, Test_Engine/Properties/AssemblyInfo.cs, Test_Engine/Test_Engine.csproj, Test_Toolkit.sln, Test_oM/Properties/AssemblyInfo.cs, Test_oM/Test_oM.csproj, docs/CODEOWNERS, docs/PULL_REQUEST_TEMPLATE.md
=> Add solution file

Test_Engine/Properties/AssemblyInfo.cs, Test_Engine/Query/TestDataOfType.cs, Test_Engine/Test_Engine.csproj, Test_Toolkit.sln, Test_oM/Properties/AssemblyInfo.cs
Closes #3 
- Adding method for extracting TestData of specific type
https://burohappold.sharepoint.com/:f:/s/BHoM/EoA0r7ykUGtBo_67-Z0Te6kBXxL1q-bd24UY_8VrGhJMRw?e=LFWT8J
=> Method for extracting test data of type

Test_Engine/Compute/CheckProjectStructure.cs, Test_Engine/Compute/CheckReferences.cs, Test_Engine/Compute/RunChecks.cs, Test_Engine/Convert/ToSyntaxTree.cs, Test_Engine/Modify/Merge.cs, Test_Engine/Query/Checks/IsValidConvertMethodName.cs, Test_Engine/Query/Checks/IsValidCreateMethodName.cs, Test_Engine/Query/Checks/NameMatchesFileName.cs, Test_Engine/Query/Checks/NamespaceMatchesFilePath.cs, Test_Engine/Query/DirectlyInherits.cs, Test_Engine/Test_Engine.csproj
Closes #25
Closes #12 
Closes #11 
Closes #15 
Closes #22 
Closes #16 
Closes #23 
- Ensures Namespaces match their folder structure
- Ensures folders meet the compliance guidance
- Ensures method names match their file name
- Ensures object names match their file name
- Checks references are set correctly
- Allows `IImmutable` objects to have constructors without failing compliance
=> File compliance

Test_Engine/Query/Checks/ContainsCopyright.cs, Test_Engine/Query/Checks/HasCorrectAttributes.cs, Test_Engine/Query/ContainsCopyright.cs
Fixes #9 
- Check a range of copyright years if no year is provided, check a specific year if it is provided
- Downgrade attribute errors to warnings for the time being
=> Check a range of copyrights

Test_Engine/Compute/RunChecks.cs, Test_Engine/Modify/Merge.cs, Test_Engine/Query/Checks/HasCorrectAttributes.cs, Test_Engine/Query/Checks/IsValidModifyMethod.cs, Test_Engine/Query/Checks/ModifyReturnsSameType.cs, Test_Engine/Query/GetIdentifier.cs, Test_Engine/Test_Engine.csproj
Closes #31 
Closes #32 
Closes #34 
Closes #36 
- Made various of the Spans created for errors more specific instead of an entire method.
- Added Modify method check on matching return type and input type
- Fixed poor performance caused by using `BH.Engine.Reflection.Query.BHoMMethodList()`
=> Correct Error spans, performance improvement and additional modify check

Test_Profiling/App.config, Test_Profiling/Diffing_Engine/GenerateRandomObjs.cs, Test_Profiling/Diffing_Engine/Profiling01.cs, Test_Profiling/Diffing_Engine/Test01.cs, Test_Profiling/Diffing_Engine/Utils/GenerateRandomObjs.cs, Test_Profiling/Program.cs, Test_Profiling/Properties/AssemblyInfo.cs, Test_Profiling/Test_Profiling.csproj, Test_Toolkit.sln
https://github.com/BHoM/BHoM/pull/601
https://github.com/BHoM/BHoM_Engine/pull/1293/
Closes #40, closes #39
=> Create Test_Profiling project and port former Test_Engine/Diffing_Engine functionality

Test_Engine/Compute/CheckProjectStructure.cs, Test_Engine/Compute/CheckReferences.cs, Test_Engine/Compute/RunChecks.cs, Test_Engine/Convert/ToText.cs, Test_Engine/Create/Error.cs, Test_Engine/Create/LineSpan.cs, Test_Engine/Create/Location.cs, Test_Engine/Query/Checks/ContainsCopyright.cs, Test_Engine/Query/ContainsCopyright.cs, Test_Engine/Test_Engine.csproj, Test_Profiling/Diffing_Engine/Test01.cs, Test_Test/AdapterTests.cs, Test_Test/EngineTests.cs, Test_Test/oMTests.cs, Test_oM/Location.cs, Test_oM/Test_oM.csproj
=> Add Location object and ToText methods

Test_Engine/Query/Checks/ObjectHasOnlyProperties.cs, Test_Engine/Query/DirectlyInherits.cs, Test_Engine/Query/GetDelaringClass.cs, Test_Engine/Query/IsImmutable.cs, Test_Engine/Test_Engine.csproj, Test_oM/Attributes/ConditionAttribute.cs, Test_oM/Attributes/ErrorLevelAttribute.cs, Test_oM/Attributes/IsPublicAttribute.cs, Test_oM/Attributes/MessageAttribute.cs, Test_oM/Attributes/PathAttribute.cs
Closes #23 
As part of #38 constructors flagged errors on Immutable objects again
=> Allow Constructors on Immutable objects

.ci/check-all-depandants.yml, .ci/check-core.yml, .ci/check-installer.yml, .ci/run-compliance-tests.yml, .ci/testSettings.runsettings, BuildInstaller.ps1, BuildPrimarySolution.ps1, BuildTest.ps1, CloneAndBuildCore.ps1, CloneAndBuildDependants.ps1, CloneAndBuildDependencies.ps1, CloneAndBuildInstaller.ps1, CloneAndBuildRepo.ps1, CloneInstaller.ps1, CloneTest.ps1, MovePRFiles.ps1, testSettings.runsettings
=> Add CI scripts

.ci/check-all-depandants.yml, .ci/check-core.yml, .ci/run-compliance-tests.yml
=> Update yml files

CloneAndBuildRepoWithMerge.ps1
=> Fix output writing

CloneAndBuildCore.ps1, CloneAndBuildDependants.ps1, CloneAndBuildDependencies.ps1
=> Update Dependant CI Checks to merge with master

MovePRFiles.ps1, Test_Engine/Compute/CheckReferences.cs
Fixes #70 
Fixes #74 
- Ensures BHoM references are set to not copy local
- Ensures output paths are set to `..\Build\`
=> Enhance .csproj checks

Test_Test/AdapterTests/InputParameterStartsLower.cs
Fixes #44 
Most warnings were resolved in a previous PR but one was outstanding which is resolved here.
=> Resolve compiler warnings

Test_Test/AdapterTests/CheckProjectFile.cs, Test_Test/AdapterTests/ContainsCopyright.cs, Test_Test/EngineTests/CheckProjectFile.cs, Test_Test/Test_Test.csproj, Test_Test/oMTests/CheckProjectFile.cs
=> Add unit tests for checking project files

Test_Test/EngineTests/NamespaceMatchesFilePath.cs, Test_Test/oMTests/NamespaceMatchesFilePath.cs
=> Disable namespace checks

MovePRFiles.ps1
=> Fix MovePRFiles bug

Test_Engine/Query/IsEqual.cs, Test_Engine/Test_Engine.csproj, Test_Engine/packages.config
=> Add IsEqual method

Test_Engine/Properties/AssemblyInfo.cs, Test_Profiling/Properties/AssemblyInfo.cs, Test_Test/Properties/AssemblyInfo.cs, Test_oM/Properties/AssemblyInfo.cs
=> Update assembly file version to 3.1.0.0

CodeComplianceTest_Engine/Query/AllChecks.cs, CodeComplianceTest_Engine/Query/Checks/CreateMethodFileNameMatchesReturnType.cs
=> Allow Create methods to return a List of types that match the filename

.ci/run-compliance-tests.yml
=> Update template file

CodeComplianceTest_Engine/Query/Checks/HasDescriptionAttribute.cs, CodeComplianceTest_Engine/Query/Checks/HasOutputAttribute.cs
Closes #119 
Limit HasDescriptionAttribute and HasOutputAttribute checks to public methods only
=> Ignore Description and Output attribute check on private methods

CodeComplianceTest_Test/AdapterTests/HasValidCopyright.cs, CodeComplianceTest_Test/EngineTests/HasValidCopyright.cs, CodeComplianceTest_Test/oMTests/HasValidCopyright.cs
=> Turn off copyright checks

BuildTest.ps1, CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Test/CodeComplianceTest_Test.csproj, InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj, Test_Profiling/Test_Profiling.csproj, Test_Toolkit.sln, Test_oM/Test_oM.csproj
Fixes #125 
This should only build `CodeComplianceTest_Engine`, `CodeComplianceTest_Test`, and `Test_oM` when using the additional config.
=> Add compliance build config

CodeComplianceTest_Engine/Compute/Check.cs, CodeComplianceTest_Engine/Query/HasValidCopyright.cs, CodeComplianceTest_Test/AdapterTests/HasValidCopyright.cs, CodeComplianceTest_Test/EngineTests/HasValidCopyright.cs, CodeComplianceTest_Test/oMTests/HasValidCopyright.cs
Fixes #136 
First commit has a deliberate change to copyright to check that compliance report reports it as a failure
=> Turn on copyright check

CodeComplianceTest_Engine/Query/Checks/HasDescriptionAttribute.cs, CodeComplianceTest_Engine/Query/Checks/HasMatchingInputDescription.cs, CodeComplianceTest_Engine/Query/Checks/HasOutputAttribute.cs
=> Remove requirement for deprecated methods to have descriptions

CodeComplianceTest_Engine/Query/Checks/HasMatchingInputDescription.cs
Fixes #146 
Have added @adecler as a reviewer in case this is something which blocks you overnight and you fancy reviewing/merging to unblock, otherwise happy to wait for @IsakNaslundBh or @awakeman to review in the morning :smile:
=> Update HasMachingInputDescription to account for new quantities attributes

CodeComplianceTest_Engine/Query/Checks/HasMatchingInputDescription.cs, CodeComplianceTest_Engine/Query/Checks/InputAttributeMatchesParameter.cs
Closes #151 
Use grasshopper compliance script
=> Fix parameter count of InputAttribute

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/DynamicChecks/AdapterCreateMethodIsValid.cs, CodeComplianceTest_Engine/Query/DynamicChecks/AdapterReadMethodIsValid.cs
Fixes #141 
This will likely conflict with #145 but that's part of a wider discussion whereas this is ready to go.
=> Add Adapter Create and Read method compliance

CodeComplianceTest_Engine/Query/Checks/IsValidConvertMethodName.cs
=> Allow for Interface convert methods

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/AttributeHasEndingPunctuation.cs, CodeComplianceTest_Engine/Query/StringEndsWithPunctuation.cs, CodeComplianceTest_Test/AdapterTests/AttributeHasEndingPunctuation.cs, CodeComplianceTest_Test/CodeComplianceTest_Test.csproj, CodeComplianceTest_Test/EngineTests/AttributeHasEndingPunctuation.cs, CodeComplianceTest_Test/oMTests/AttributeHasEndingPunctuation.cs
=> Add compliance check for punctuation on documentation

CodeComplianceTest_Engine/Query/Checks/InputParameterStartsLower.cs
=> Change error message on input parameters

CodeComplianceTest_Engine/Query/Checks/HasPublicGet.cs, CodeComplianceTest_Engine/Query/Checks/PropertyAccessorsHaveNoBody.cs, CodeComplianceTest_Engine/Query/PropertyGetAccessor.cs
=> Fix null exception bug in property accessors if they are null

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/DynamicChecks/IsValidQuantityInputAttribute.cs
=> Add quantity attribute compiled compliance check

CodeComplianceTest_Test/AdapterTests/AttributeHasEndingPunctuation.cs, CodeComplianceTest_Test/EngineTests/AttributeHasEndingPunctuation.cs, CodeComplianceTest_Test/oMTests/AttributeHasEndingPunctuation.cs
=> Turn off punctuation checking

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/NameContainsFileName.cs, CodeComplianceTest_Test/CodeComplianceTest_Test.csproj, CodeComplianceTest_Test/EngineTests/NameContainsFileName.cs
=> Change compliance check for method names matching filenames

CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs
=> Turn off checking of IsExtensionMethod for Compute methods

CodeComplianceTest_Test/RunTest.cs
=> Simplify error message outputs for CI

InteroperabilityTest_Engine/Query/IsEqual.cs
https://github.com/BHoM/BHoM/pull/715
https://github.com/BHoM/BHoM_Engine/pull/1534
Closes #190
=> InteroperabilityTest_Engine: Align to changes in BH.oM.Diffing.DiffConfig

Test_Engine/Compute/DummyObject.cs, Test_Engine/Properties/AssemblyInfo.cs, Test_Engine/Query/IsEqual.cs, Test_Engine/Test_Engine.csproj, Test_Engine/app.config, Test_Engine/packages.config, Test_Toolkit.sln
Not really a dependency but good to be aware of the mirror PR: https://github.com/BHoM/BHoM_Engine/pull/1655
See https://github.com/BHoM/BHoM_Engine/pull/1655 for more details
=> Test_Engine: Migrate Dummy and IsEqual methods from Reflection Engine

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/IsVirtualProperty.cs, CodeComplianceTest_Test/CodeComplianceTest_Test.csproj, CodeComplianceTest_Test/oMTests/IsVirtualProperty.cs, Test_oM/Location.cs
Fixes #209
N/A - see reports below
Wiki page is up [here](https://github.com/BHoM/documentation/wiki/IsVirtualProperty)
=> Add IsVirtualProperty check

CodeComplianceTest_Engine/Query/Checks/IsVirtualProperty.cs, Test_oM/ComplianceResult.cs
Fixes #224 
See comments once run
=> Prevent Virtual keyword checking on interface classes

CodeComplianceTest_Engine/Compute/CheckReferences.cs
=> Add LifeCycleAssesment to core projects

CodeComplianceTest_Engine/Compute/CheckReferences.cs
=> Fix adapter core project reference checking

CodeComplianceTest_Engine/Query/Checks/IsValidConvertMethodName.cs
=> Turn on convert method checks for Adapter projects

CodeComplianceTest_Engine/Query/Checks/AttributeHasEndingPunctuation.cs
Fixes #183 
Run standard script with attributes on
This check is not turned on so won't affect PRs, as it is only used in script checks.
=> Fix erroneous punctuation check for multi output

CodeComplianceTest_Test/CodeComplianceTest_Test.csproj, CodeComplianceTest_Test/EngineTests/HasSingleNamespace.cs, CodeComplianceTest_Test/oMTests/HasSingleNamespace.cs
=> Turn on HasSingleNamespace check

CodeComplianceTest_Engine/Compute/CheckReferences.cs
=> Update csproj checking

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/CreateMethodFileNameMatchesReturnType.cs, CodeComplianceTest_Engine/Query/Checks/IsValidCreateMethod.cs, CodeComplianceTest_Engine/Query/Checks/IsValidCreateMethodName.cs, CodeComplianceTest_Test/CodeComplianceTest_Test.csproj, CodeComplianceTest_Test/EngineTests/IsValidCreateMethod.cs
=> Update Create Method compliance checks

CodeComplianceTest_Engine/Compute/CheckReferences.cs
=> CSProj checks for localisation and project references

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj, Test_Engine/Test_Engine.csproj, Test_oM/Test_oM.csproj
Closes #243 
Closes #244 
Closes #245 
Fixes compliance of CSProj files.
Some copy locals kept for CodeComplianceTest_Test
=> Fix compliance issues of CSProj files

Test_Engine/Compute/DummyObject.cs, Test_oM/Attributes/PathAttribute.cs
See https://github.com/BHoM/BHoM_Engine/pull/1756 for more details
=> Test_Toolkit: fix serialisation-related problems

Test_oM/Test_oM.csproj, Test_oM/UnitTests/TestData.cs, Test_oM/UnitTests/UnitTest.cs
Closes #251
Adding UnitTest object to store input, method and output for datadriven unit tests.
=> Add UnitTest object and TestData object

CodeComplianceTest_Engine/Query/Checks/IsVirtualProperty.cs
=> Fix VirtualProperty check

CodeComplianceTest_Engine/Query/Checks/IsValidCreateMethod.cs
Fixes #258 
Wiki to be updated separately.
=> Update IsValidCreateMethod check

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
=> Copy over relevant DLLs

CodeComplianceTest_Engine/Compute/CheckReferences.cs
=> Fix for BHoMBot-CI

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Test/CodeComplianceTest_Test.csproj
Fixes #271 
Check file changes match those on the issue, and the toolkit compiles on your machine
=> Fix compilation compliance

InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj
Closes #276
Fixing Dataset post build to point to ProgramData instead of Appdata
=> Fix Dataset post build

CodeComplianceTest_Engine/Query/Checks/AttributeHasEndingPunctuation.cs
=> Provide documentation link for AttributeHasEndingPunctuation

.github/CODEOWNERS, CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/HasUniqueMultiOutputAttributes.cs, CodeComplianceTest_Engine/Query/Checks/HasValidMultiOutputAttributes.cs
Fixes #284 
https://github.com/BHoM/documentation/wiki/HasValidMultiOutputAttribute - documentation of HasValidMultiOutputAttribute check
https://github.com/BHoM/documentation/wiki/HasUniqueMultiOutputAttribute - documentation of HasUnqiueMultiOutputAttribute
=> Fix bug in multi output checking

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/InputAttributeHasMatchingParameter.cs, CodeComplianceTest_Engine/Query/Checks/IsUsingCustomData.cs, CodeComplianceTest_Engine/Query/Checks/PreviousInputNamesAttributeHasMatchingParameter.cs, CodeComplianceTest_Engine/Query/Checks/PreviousInputNamesAttributeIsUnique.cs, CodeComplianceTest_Engine/Query/PreviousInputNamesAttributes.cs
Fixes #286
Fixes #281 
https://github.com/BHoM/documentation/wiki/PreviousInputNamesAttributeHasMatchingParameter
https://github.com/BHoM/documentation/wiki/PreviousInputNamesAttributeIsUnique
https://github.com/BHoM/documentation/wiki/IsUsingCustomData
=> Add compliance checks for PreviousInputNames usage

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
Fixes #292 
https://github.com/BHoM/documentation/wiki/HasValidPreviousVersionAttribute - documentation for the check.
=> Add HasValidPreviousVersionAttribute test

CodeComplianceTest_Engine/Query/Checks/InputAttributeHasMatchingParameter.cs, CodeComplianceTest_Engine/Query/Checks/InputAttributeIsUnique.cs, CodeComplianceTest_Engine/Query/Checks/IsInputAttributePresent.cs, CodeComplianceTest_Engine/Query/InputAttributes.cs
Fixes #159 
Documentation will be updated accordingly.
=> Add input from property allowances and checks

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/HasConstructor.cs, CodeComplianceTest_Engine/Query/Checks/HasOneConstructor.cs, CodeComplianceTest_Engine/Query/Checks/HasUniqueMultiOutputAttributes.cs, CodeComplianceTest_Engine/Query/Checks/HasValidConstructor.cs, CodeComplianceTest_Engine/Query/Checks/HasValidMultiOutputAttributes.cs, CodeComplianceTest_Engine/Query/Checks/IsValidIImmutableObject.cs, CodeComplianceTest_Engine/Query/HasConstructor.cs
Fixes #103 
https://github.com/BHoM/documentation/wiki/HasConstructor
https://github.com/BHoM/documentation/wiki/HasOneConstructor
https://github.com/BHoM/documentation/wiki/HasValidConstructor
https://github.com/BHoM/documentation/wiki/IsValidIImmutableObject
=> Add compliance tests for constructions and IImutable objects

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/DynamicChecks/IsValidDataset.cs
Fixes #187 
https://github.com/BHoM/documentation/wiki/IsValidDataset
=> Add ability to check Dataset compliance

InteroperabilityTest_Engine/Compute/PushPullCompare.cs, Test_Engine/Query/IsEqual.cs, UnitTest_Engine/Compute/CheckTest.cs
https://github.com/BHoM/BHoM_Engine/pull/2105
Closes #302
=> Align to changes in Diffing_Engine

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/DynamicChecks/ImplementsBaseOption.cs, CodeComplianceTest_Engine/Query/DynamicChecks/InputFromPropertyMatchesProperty.cs, CodeComplianceTest_Engine/Query/Signature.cs
Fixes #298 
Fixes #91 
Still need to do documentation, but these checks aren't being rolled out just yet, just here to help people do stuff within Grasshopper initially.
=> Add Dynamic check for InputFromPropertyMatchesProperty and ImplementsBaseOption

CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
=> Uptick to 4.1

Test_Engine/Compute/DummyObject.cs, Test_Engine/Query/IsEqual.cs
Supports https://github.com/BHoM/BHoM_UI/pull/348
A few minor things needed to be fixed for the UI CI tests to work without crashing. See commit names. 
Make sure that the CI tests in the UI can run properly. The changes on `IsEqual` are mainly some trivial changes that can be validated by code inspection. The changes to `DummyObject` are more complex so the best way to test that is really to make sure that any type of object can be created through the use of UI CI test
=> Fixes needed for CI tests on the UI

CodeComplianceTest_Engine/Query/Checks/HasValidCopyright.cs
=> Fix bug in copyright checking

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/DynamicChecks/ConvertMethodIsValid.cs
Closes #84 
Starting with Convert method compliance, builds out compliance check framework for checks that need compiled assemblies to run. Most notably access to the class hierarchy information as with #84 (To* methods should take a **BHoM object**, From* methods should return a **BHoM object**)
=> Add Dynamic Checks

UnitTest_Engine/Compute/MergeUnitTests.cs, UnitTest_Engine/UnitTest_Engine.csproj
Closes #316
Adding method for merging unittests with the same method.
Raising as draft to help with review and testing of https://github.com/BHoM/BHoM_UI/pull/356 . ~~Will add proper descriptions and test files when I find time next week.~~
Test file requires https://github.com/BHoM/BHoM_UI/pull/356 to run.
https://burohappold.sharepoint.com/:f:/s/BHoM/EsjfKs1LBRVCkCsucHj9f00Bg2GkeX79iNnvGb2RM-BMhg?e=btMdF1
=> Adding merge UnitTests method

TestRunner/Program.cs, TestRunner/TestRunner.csproj, Test_Engine/Create/FailResult.cs, Test_Engine/Create/PassResult.cs, Test_Engine/Query/FullMessage.cs, Test_Engine/Query/IsEqualOrMoreSevere.cs, Test_Engine/Query/MostSevereStatus.cs, Test_Engine/Test_Engine.csproj, Test_Toolkit.sln, UnitTest_Engine/Compute/CheckTest.cs, UnitTest_Engine/Compute/Run.cs, UnitTest_Engine/Query/FullMessage.cs, UnitTest_Engine/UnitTest_Engine.csproj, UnitTest_oM/Properties/AssemblyInfo.cs, UnitTest_oM/Results/ComparisonDifference.cs, UnitTest_oM/UnitTest_oM.csproj
Closes #319 
Closes #320 
Closes #318 
Closes #308 
Refactor of the UnitTest checking methods to return the new TestResult object.
https://burohappold.sharepoint.com/:f:/s/BHoM/EkatzhFSfEFFkFGfP13IgTIBXoY5p72_0yXfdqo4kXbYBg?e=vKkrac
@adecler I also had to update some of your methods in the Test_Engine as well as in the TestRunner to get the code to compile. That might need some additional tweaks.
=> Refactor running of unit tests

Test_Engine/Query/FullMessage.cs
Closes #324 
See issue for description 🤦
=> Fixing stack overflow issue

CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
=> Uptick to 4.2

CodeComplianceTest_Engine/Query/Checks/HasSingleClass.cs, CodeComplianceTest_Engine/Query/Checks/HasSingleNamespace.cs, CodeComplianceTest_Engine/Query/Checks/HasUniqueMultiOutputAttributes.cs, CodeComplianceTest_Engine/Query/Checks/HasUniqueOutputAttribute.cs, CodeComplianceTest_Engine/Query/Checks/HasValidMultiOutputAttributes.cs, CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs, CodeComplianceTest_Engine/Query/Checks/IsUsingCustomData.cs
Fixes #342 
Fixes some checks that were running on `Objects` files FYI @peterjamesnugent 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Test_Toolkit/%23343-MultiOutputComplianceCheck?csf=1&web=1&e=1MKMPy
=> Fix multi output check

CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
=> Uptick to 4.3

CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
=> Uptick to 5.0

UnitTest_oM/UnitTest_oM.csproj
In line with the upgrade to .Net Standard 2.0 on the core.
=> Update UnitTest_oM to 4.7.2 net framework version

CodeComplianceTest_Engine/Compute/CheckReferences.cs
Spotted by @pawelbaran on one of his PRs.
=> Downgrade an error that should have been a warning from the off

CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
=> Uptick previous version attribute check

UnitTest_Engine/Compute/StoreUnitTest.cs, UnitTest_Engine/Create/Dataset/UnitTestDataSet.cs, UnitTest_Engine/UnitTest_Engine.csproj
Closes #366
Adding methods wo help create proper, compliant UnitTest Datasets and a method to put them in the correct folder of a repo.
=> UnitTest_Engine: Add methods for help creation of unit test datasets

UnitTest_Engine/Compute/CheckTest.cs
Adds a new method to handle file name input for unit tests - vital for Gen2 of BHoMBot.
=> Add CheckTest method that takes in a file name to aid BHoMBot

CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
=> Uptick HasValidPreviousVersionAttribute to 5.2

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Compute/CheckProjectStructure.cs, CodeComplianceTest_Engine/Compute/CheckReferences.cs, CodeComplianceTest_Engine/Compute/RunChecks.cs, CodeComplianceTest_Engine/Query/DynamicChecks/ImplementsBaseOption.cs, CodeComplianceTest_Engine/Query/DynamicChecks/InputFromPropertyMatchesProperty.cs, CodeComplianceTest_Engine/Query/DynamicChecks/IsValidDataset.cs
Tidies up the using statements for CodeComplianceTest_Engine for better usage with BHoMBot Gen2.
=> Tidy up usings

CodeComplianceTest_Engine/Compute/CheckAssemblyInfo.cs, CodeComplianceTest_Engine/Compute/CheckProjectFile.cs, CodeCompliance_oM/CSProject/ProjectFile.cs
Fixes #389 some more after testing with the bot
=> Update compliance check for postbuild

CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
=> Final fix for #389

CodeComplianceTest_Engine/Compute/CheckAssemblyInfo.cs, CodeComplianceTest_Engine/Properties/AssemblyInfo.cs, CodeComplianceTest_Test/Properties/AssemblyInfo.cs, CodeCompliance_oM/Properties/AssemblyInfo.cs, InteroperabilityTest_Engine/Properties/AssemblyInfo.cs, InteroperabilityTest_oM/Properties/AssemblyInfo.cs, TestRunner/Properties/AssemblyInfo.cs, Test_Engine/Properties/AssemblyInfo.cs, UnitTest_Engine/Properties/AssemblyInfo.cs, UnitTest_oM/Properties/AssemblyInfo.cs
Update Assembly Information to include description
=> Update Assembly Information

CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
To avoid confusion for this milestone
=> Downgrade postbuild from error to warning

CodeComplianceTest_Engine/Query/CurrentVersion.cs
Uptick the compliance checks for 6.0 milestone start.
=> Uptick checks for 6.0 milestone

CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
=> Reworded the error message for SetSpecificVersion in project file

UnitTest_Engine/Create/Dataset/UnitTestDataSet.cs
=> Remove requirement to provide a source link by default for Unit Test datasets

CodeComplianceTest_Engine/Query/FullMessage.cs
=> Update documentation link

CodeCompliance_oM/CodeComplianceTest_oM.csproj
=> Project compliance updated.

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/IsDocumentationURLValid.cs
Fixes #129 
New wiki page [here](https://bhom.xyz/documentation/DevOps/Code%20Compliance%20and%20CI/Compliance%20Checks/IsDocumentationURLValid/)
=> Add compliance check for documentation URL validity

dependencies.txt
=> Update dependencies file

CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
Closes #426
The updates as listed in the issue have been addressed. The CSProject compliance check was updated to include .Net 4.8 and the reference to the DLL files have been changed.
=> CSProject compliance updates

CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
=> Updates to Project Compliance checks

NUnit_oM/Assertion.cs, NUnit_oM/Assertions.cs, NUnit_oM/Environment.cs, NUnit_oM/Failure.cs, NUnit_oM/NUnit_oM.csproj, NUnit_oM/Properties.cs, NUnit_oM/Property.cs, NUnit_oM/Setting.cs, NUnit_oM/Settings.cs, NUnit_oM/TestCase.cs, NUnit_oM/TestRun.cs, NUnit_oM/TestSuite.cs
=> Update compliance of objects to include IObject

CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj, CodeComplianceTest_Engine/Query/Checks/InputAttributesAreInOrder.cs
=> Add compliance check to ensure input attributes are in the same order as input parameters

NUnit_Engine/Convert/TestResult.cs, NUnit_oM/Reason.cs, NUnit_oM/TestSuite.cs
=> Update NUnit_oM for changes based on BHoM_Engine testing

CodeComplianceTest_Engine/Query/DynamicChecks/IsValidDataset.cs, CodeComplianceTest_Engine/Query/FullMessage.cs
Closes #448 
- Updated URL to call Query.DocumentationURL
=> Updated URLs to call `Query.DocumentationURL`

CodeComplianceTest_Engine/Query/DynamicChecks/IsValidQuantityInputAttribute.cs
Closes #452 
- Updated name of the `InputClassificationAttribute` attribute following its name change in Bhom_Engine.
- Simply build the solution and see if it works.
- Updated name of an attribute following the name change in Bhom_Engine
=> Updated reference to InputClassificationAttribute

CodeComplianceTest_Engine/Query/CurrentVersion.cs
=> Uptick to 6.3

CodeComplianceTest_Engine/Query/Checks/IsDocumentationURLValid.cs
=> Switch web URL checker to match the bot uptime checker

CodeComplianceTest_Engine/Query/CurrentVersion.cs
=> Uptick to 7.0

CodeComplianceTest_Engine/Query/CurrentVersion.cs
=> Uptick to 7.1

CodeComplianceTest_Engine/Compute/CheckAssemblyInfo.cs
Closes #464 
Test by compiling.
- Reinstated lines that have been removed in error, that resulted in the toolkit not compiling
=> Reinstate lines removed in error by BHoMBot

CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs
=> Add DateTime exception to IsExtensionMethod

CodeComplianceTest_Engine/Query/CurrentVersion.cs
=> Uptick to 7.2

CodeComplianceTest_Engine/Query/CurrentVersion.cs
Closes #475
Upticks to current versions to 7.3 for checks. No to be merged before assembly file versions have been updated across all relevant repositories.
=> Uptick to 7.3

InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj, InteroperabilityTest_Engine/packages.config, Test_Engine/Test_Engine.csproj, Test_Engine/packages.config
Closes #478
Install fresh Alpha and try building.
=> Postbuild of Test_Engine fixed

Test_Engine/Compute/DummyObject.cs, Test_Engine/Compute/LoadRevitAssemblies.cs, Test_Engine/Compute/ToJsonWithChecks.cs, Test_Engine/Compute/TryToJsonAndFromJsonAndCheckIfEqual.cs, Test_Engine/Query/VersioningAdapterConstructorList.cs, Test_Engine/Query/VersioningMethodList.cs, Test_Engine/Query/VersioningTypeList.cs, Test_Engine/Test_Engine.csproj
Closes #480
Adds code to help with generating the json files for the versioning tests.
Gives various repsonses as to things that have failed, or could cause other issues.
Found here:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Test_Toolkit/%23481-AddCodeToHelpProduceVersioningTestSets?csf=1&web=1&e=jaUbOu
=> Test_Engine: Add code to help produce versioning test sets

.ci/unit-tests/Example_Engine/Example_Engine.csproj, .ci/unit-tests/NUnit_Engine_Tests/NUnit_Engine_Tests.csproj, .ci/unit-tests/NUnit_Engine_WrongReferencesTests/NUnit_Engine_WrongReferencesTests.csproj, CodeComplianceTest_Engine/Properties/AssemblyInfo.cs, CodeComplianceTest_Engine/Query/CurrentVersion.cs, CodeCompliance_oM/CodeComplianceTest_oM.csproj, CodeCompliance_oM/Properties/AssemblyInfo.cs, InteroperabilityTest_Engine/Properties/AssemblyInfo.cs, InteroperabilityTest_oM/InteroperabilityTest_oM.csproj, InteroperabilityTest_oM/Properties/AssemblyInfo.cs, NUnit_Engine/NUnit_Engine.csproj, NUnit_oM/NUnit_oM.csproj, TestRunner/Properties/AssemblyInfo.cs, TestRunner/TestRunner.csproj, Test_Engine/Properties/AssemblyInfo.cs, UnitTest_Engine/Compute/MergeUnitTests.cs, UnitTest_Engine/Properties/AssemblyInfo.cs, UnitTest_oM/Properties/AssemblyInfo.cs, UnitTest_oM/UnitTest_oM.csproj
Update assembly file version to 8.0.0.0 and AssemblyVersion to 8.0.0.0
Remove previous version attributes for 8.0
Update expected assembly versions in project compliance checks
=> Start of milestone changes for 8.0 

Test_Engine/Compute/DummyObject.cs
Closes #494
Fixes the issue of creation of dummy objects for generic, immutable types.
Will remove the warning raised here https://github.com/BHoM/BHoM_Engine/pull/3447/checks?check_run_id=35566716430
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Test_Toolkit/%23496-EnableCreationOfGenericImmutableDummyObjects?csf=1&web=1&e=GjKRuP
=> Correctly set concrete generic type for immutable objects
