BHoM/Test_Toolkit

- Test_Engine/Query/GetDelaringClass.cs
> Fix call to incorrect method in IGetDeclaringClass

- BuildInstaller.ps1
- CloneAndBuildRepoWithMerge.ps1
Fixes #60 
Installer building of repos is now done by merging `master` into any dependant branches. This makes sense to me because ultimately, the installer won't build with the PR code until it is merged into `master` so that is what we want to check with, rather than in isolation as the other checks do.
> Update installer building commands

- InteroperabilityTest_Engine/Compute/PushPullCompare.cs
- InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj
- Test_Profiling/Diffing_Engine/Test01.cs
https://github.com/BHoM/BHoM_Engine/pull/1371
https://github.com/BHoM/BHoM_Adapter/pull/164
https://github.com/BHoM/BHoM_UI/pull/167
- If you use Grasshopper: https://github.com/BHoM/Grasshopper_Toolkit/pull/440
- If you use Excel: https://github.com/BHoM/Excel_Toolkit/pull/172
- If you use Dynamo: https://github.com/BHoM/Dynamo_Toolkit/pull/188
- If your Toolkit needs Socket_Toolkit: https://github.com/BHoM/Socket_Toolkit/pull/57
- If your Toolkit needs Mongo_Toolkit: https://github.com/BHoM/Mongo_Toolkit/pull/82
- If you want the Adapter components to be automatically upgraded to their new version in your test scripts: https://github.com/BHoM/Versioning_Toolkit/pull/8
Fixes #108
> Aligning with changes in BHoMAdapter Refactoring Level 04

- CodeComplianceTest_Engine/Query/Checks/HasOutputAttribute.cs
Closes #121 
As title
https://burohappold.sharepoint.com/:f:/s/BHoM/EoPWbwmhLx1Kh5fqFizd9P4BddiDIw-AAOaEZ5oyBJjW3g?e=LHnX7X
> Don't check output attribute on methods with void return type

- CodeComplianceTest_Engine/Query/Checks/HasOutputAttribute.cs
> Fix invalid cast exception when return type is not a predefined type

- CodeComplianceTest_Engine/Query/Checks/CreateMethodFileNameMatchesReturnType.cs
Closes #142 
As per https://github.com/BHoM/Test_Toolkit/issues/142#issuecomment-587403157 
> EITHER
> 
>  - Create method file names must match their return type (e.g. Blah.cs contains only Create methods which return Blah objects)
> 
> OR
> 
>  - The Create method filepath must contain the return type AND the method name must match the file name
> Allow path to contain return type rather than only filename

- CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
- CodeComplianceTest_Engine/Query/Checks/InputAttributeIsUnique.cs
- CodeComplianceTest_Test/AdapterTests/InputAttributeIsUnique.cs
- CodeComplianceTest_Test/CodeComplianceTest_Test.csproj
- CodeComplianceTest_Test/EngineTests/InputAttributeIsUnique.cs
Closes #149 
Adds a compliance check to assert that an input attribute is the only one of a given name for a method.
https://burohappold.sharepoint.com/:f:/s/BHoM/EkB_N9Q49txFpBAtxzqL_MMB8D3KQ3au1LWawcOqeEDe_w?e=yZXVX1
> Add check that Input Attributes are unique

- CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
- CodeComplianceTest_Engine/Query/Checks/HasValidOutputAttribute.cs
- CodeComplianceTest_Engine/Query/GetName.cs
- CodeComplianceTest_Engine/Query/IsDeprecated.cs
- CodeComplianceTest_Test/AdapterTests/HasValidOutputAttribute.cs
- CodeComplianceTest_Test/CodeComplianceTest_Test.csproj
- CodeComplianceTest_Test/EngineTests/HasValidOutputAttributecs.cs
Fixes #189 
If a method has `MultiOutput` attribute then they also have to be using `Output<t1, tn>` return type. If a method has an `Output` attribute then it cannot have the `Output<t1, tn>` return type.
Full documentation can be found [here](https://github.com/BHoM/documentation/wiki/HasValidOutputAttribute)
> Add HasValidOutputAttribute test

- CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
- CodeComplianceTest_Engine/Compute/CheckReferences.cs
- CodeComplianceTest_Test/CodeComplianceTest_Test.csproj
- InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj
- Test_Engine/Test_Engine.csproj
- Test_oM/Test_oM.csproj
- UnitTest_Engine/UnitTest_Engine.csproj
https://github.com/BHoM/admin/issues/5
Fixes #261 
This updates the check to see that DLL references are set to the new ProgramData location rather than local Build folders.
Documentation is not yet updated and will be updated separately (see #262 ).
> Change project reference checking for Admin issue 5

- Test_Engine/Compute/DummyObject.cs
Closes #266
See issue for details
- To run the test shown in the issue you will need to run the latest installer and compile the `Test_Toolkit`
- I see this as a safe fix to be merge this week. Especially since the test toolkit is not part of the installer.
> Test_Engine: Prevent creation of Deprecated object when using DummyObject

- BuildTest.ps1
- CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
- CodeComplianceTest_Engine/Compute/CheckReferences.cs
- CodeComplianceTest_Engine/packages.config
- CodeComplianceTest_Test/AdapterTests/CheckProjectFile.cs
- CodeComplianceTest_Test/CodeComplianceTest_Test.csproj
- CodeComplianceTest_Test/EngineTests/CheckProjectFile.cs
- CodeComplianceTest_Test/oMTests/CheckProjectFile.cs
- Test_oM/Test_oM.csproj
- dependencies.txt
Allows the check to use the functionality coming from XML Toolkit to control CSProject files to make it easier.
> Update CSProject checks to use XML Toolkit

- CodeComplianceTest_Engine/Query/Checks/AttributeHasEndingPunctuation.cs
- CodeComplianceTest_Engine/Query/DynamicChecks/IsValidDataset.cs
Fixes a bug found in `AttributeHasEndingPunctuation` and improves the reporting in `IsValidDataset`.
> Fix punctuation check and ValidDataset reporting

- InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj
- InteroperabilityTest_Engine/packages.config
- TestRunner/App.config
- TestRunner/Program.cs
- TestRunner/Properties/AssemblyInfo.cs
- TestRunner/TestRunner.csproj
- Test_Engine/Create/FailResult.cs
- Test_Engine/Create/PassResult.cs
- Test_Engine/Test_Engine.csproj
- Test_Engine/app.config
- Test_Engine/packages.config
- Test_Toolkit.sln
- UnitTest_Engine/UnitTest_Engine.csproj
https://github.com/BHoM/BHoM/pull/1122
Provide support for closing https://github.com/BHoM/BHoM_Engine/issues/2221
- Add Create methods for FailResult and PassResult
- Fix issue with inconsistent references to `KellermanSoftware.Compare-NET-Objects`
- Add a generic test runner executable
- There was a weird bug when running the TestRunner complaining about not being able to find `KellermanSoftware.Compare-NET-Objects` version 4.66. It seems that some of the projects were using v4.65 while others were using v4.66 so I upgraded all to the latest version.
- the `TestRunner` executable is just for convenience of being able to easily run the tests locally in a way as close as possible to what the BHoMBot would experience (i.e. no interference from the UI). It's pretty basic for now and just …
> Test_Toolkit: Add basic support for creating the ci test on serialiser

- TestRunner/Program.cs
- TestRunner/TestRunner.csproj
- Test_Engine/Convert/ToEventMessage.cs
- Test_Engine/Convert/ToTestStatus.cs
- Test_Engine/Test_Engine.csproj
https://github.com/BHoM/BHoM/pull/1182
Closes #329 
Nothing too fancy, I have just added a centralised converter between debug events and `EventMessage` to avoid having to rewrite that everywhere. 
This can (and probably should) actually be merged at the same time as https://github.com/BHoM/BHoM/pull/1182.
I don't see those specific methods needing further changes so I didn't set this PR as draft. If there are further changes needed for the `Verify.sln` I'd rather do them in a separate PR.
> Adding converter between Debug Event and TestMessage

- TestRunner/TestRunner.csproj
Closes #345
See issue
Just make sure that the GetInfo component is still returning 4.2 for the current version
> Fix target build folder for TestRunner

- CodeComplianceTest_Engine/Query/Checks/EngineClassMatchesFilePath.cs
- CodeComplianceTest_Engine/Query/Checks/HasDescriptionAttribute.cs
- CodeComplianceTest_Engine/Query/Checks/HasPublicGet.cs
- CodeComplianceTest_Engine/Query/Checks/HasSingleClass.cs
- CodeComplianceTest_Engine/Query/Checks/HasSingleNamespace.cs
- CodeComplianceTest_Engine/Query/Checks/HasValidCopyright.cs
- CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs
- CodeComplianceTest_Engine/Query/Checks/IsPublicClass.cs
- CodeComplianceTest_Engine/Query/Checks/IsPublicProperty.cs
- CodeComplianceTest_Engine/Query/Checks/IsStaticClass.cs
- CodeComplianceTest_Engine/Query/Checks/IsValidConvertMethodName.cs
- CodeComplianceTest_Engine/Query/Checks/IsValidCreateMethod.cs
- CodeComplianceTest_Engine/Query/Checks/IsValidCreateMethodName.cs
- CodeComplianceTest_Engine/Query/Checks/IsValidEngineClassName.cs
- CodeComplianceTest_Engine/Query/Checks/IsVirtualProperty.cs
- CodeComplianceTest_Engine/Query/Checks/MethodNameContainsFileName.cs
- CodeComplianceTest_Engine/Query/Checks/ModifyReturnsDifferentType.cs
- CodeComplianceTest_Engine/Query/Checks/PropertyAccessorsHaveNoBody.cs
Full review of what is a warning vs and error for the 4.3 milestone was conducted and updates have been made accordingly.
A lot of classes were `[ErrorLevel(TestStatus.Error)]` by default (i.e. no attribute is == to an error), so I have added some simply for transparency for the next review to avoid the ambiguity. Those files changed which just have that added are therefore no change to the result for compliance checks.
The following checks have been upgraded from `warning` to `error`:
- HasDescriptionAttribute
The following checks have been downgraded from `error` to `warning`:
- ModifyReturnsDifferentType
> Update warnings and errors

- InteroperabilityTest_Engine/Compute/ComputePushPullCompareDifferences.cs
- InteroperabilityTest_Engine/Compute/PushPullCompare.cs
- InteroperabilityTest_Engine/InteroperabilityTest_Engine.csproj
- InteroperabilityTest_oM/InteroperabilityTest_oM.csproj
- InteroperabilityTest_oM/Settings/InteropabilityTestSettings.cs
https://github.com/BHoM/BHoM_Adapter/pull/301
Need to merge before the above PR before this. Change of strategy of where to add the new method made this toolkit depending on the above branch.
Closes #352
Adding setting object to store toolkit specific settings for running PushPullCompare
Adding method for running a PushPullCompare straight from a settings object
Changed the PushPullCOmpare method to be working with the IBHoMAdapter interface rather than the IBHoMAdapter.
https://burohappold.sharepoint.com/:f:/s/BHoM/Euu1yMnGrLxDoi2BGc4nHogB_a7P9pYg0ldMq--ZUOjauw?e=7qkMus
> Adding InteropabilityTestSettings object

- InteroperabilityTest_Engine/Compute/PushPullCompare.cs
https://github.com/BHoM/BHoM_Adapter/pull/303
Closes #354 
Adding call to the Exit command to the adapter as a final clean-up step after the PushPullCompare has been run.
> PushPullCompare from file setting to exit the adapter

- Test_Engine/Query/IsEqual.cs
- UnitTest_Engine/Compute/CheckTest.cs
- UnitTest_Engine/Compute/Run.cs
Closes #359
Closes #360 
Closes #361 
Ensuring that casting of lists to correct types is recursive.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FTest%5FToolkit%2F%23360%2DFixCheckingOfMultiLayerList
> UnitTest_Engine: Fix casting of objects to correct type for recursive lists

- CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
- CodeComplianceTest_Engine/Compute/CheckAssemblyInfo.cs
- CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
- CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
- CodeComplianceTest_Engine/Query/CurrentVersion.cs
- CodeCompliance_oM/CSProject/ProjectFile.cs
Fixes #389 
This introduces the ability to  check `AssemblyInfo.cs` files for their compliance to our guidelines on `AssemblyVersion`, `AssemblyFileVersion`, and `AssemblyDescription`.
Also updates the `CSProject` check to include the above as well for the new style project files which replace `AssemblyInfo.cs`.
> Update Project checking to include assembly file information

- UnitTest_Engine/Compute/MergeUnitTests.cs
- UnitTest_Engine/Compute/StoreUnitTest.cs
- UnitTest_Engine/Create/Dataset/UnitTestDataSet.cs
Closes #401 
Closes #333 
Additional fix for #399 
- Change grouping of MergeUnitTest to rely on json representation rather than straight reference that was causing issues with modified UTs due to deepcloning.
- Filter out null UTs before merge
- Additional check for valid source link changed for #399 
https://burohappold.sharepoint.com/:f:/s/BHoM/EjJYNYuLl2lLpMW8KOMnb7QBgfept7lQUvJDYiAaXMAKOw?e=PgE8aL
> Fix merge UnitTest

- TestRunner/Program.cs
Closes #406
Making TestRunner able to run versioning verification after changes in https://github.com/BHoM/Versioning_Toolkit/pull/201
Made the filtering quite explicit to only allow for methods with single boolean input on top of the previously accepted 0 argument methods. Not sure if we want to expand the scope even further or not.
To be tested by use of the TestRunner
> Update TestRunner to accept methods with single boolean inputs

- CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs
Fixes #385 
`BHoM_Engine/Query/IsAdapterAssembly.cs` contains a `this string` method (line 48) which can be used to test with.
Try with a few types though if you wish to confirm. However, system types should no longer be flagged as needing the `this` keyword.
Took the exclusion list from [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types).
> Change IsExtensionMethod to ignore system types

- CodeComplianceTest_Engine/CodeComplianceTest_Engine.csproj
- CodeComplianceTest_Engine/app.config
- CodeComplianceTest_Engine/packages.config
- Test_Toolkit.sln
> Upgrade System.Runtime.CompilerServices.Unsafe.dll to 5.0.0.0

- CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs
> Fix for list/dictionary objects not needing 'this' keyword if they are only for system types

- CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
- CodeComplianceTest_Engine/Query/Checks/EngineClassMatchesFilePath.cs
- CodeComplianceTest_Engine/Query/Checks/HasConstructor.cs
- CodeComplianceTest_Engine/Query/Checks/HasOneConstructor.cs
- CodeComplianceTest_Engine/Query/Checks/HasPublicGet.cs
- CodeComplianceTest_Engine/Query/Checks/HasValidConstructor.cs
- CodeComplianceTest_Engine/Query/Checks/HasValidPreviousVersionAttribute.cs
- CodeComplianceTest_Engine/Query/Checks/HiddenInputsAreLast.cs
- CodeComplianceTest_Engine/Query/Checks/InputAttributesAreInOrder.cs
- CodeComplianceTest_Engine/Query/Checks/IsDocumentationURLValid.cs
- CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs
- CodeComplianceTest_Engine/Query/Checks/IsPublicClass.cs
- CodeComplianceTest_Engine/Query/Checks/IsStaticClass.cs
- CodeComplianceTest_Engine/Query/Checks/IsUsingCustomData.cs
- CodeComplianceTest_Engine/Query/Checks/IsValidEngineClassName.cs
- CodeComplianceTest_Engine/Query/Checks/IsValidIImmutableObject.cs
- CodeComplianceTest_Engine/Query/Checks/PreviousInputNamesAttributeHasMatchingParameter.cs
- CodeComplianceTest_Engine/Query/Checks/PreviousInputNamesAttributeIsUnique.cs
- CodeComplianceTest_Engine/Query/Checks/UIExposureHasDefaultValue.cs
Closes #482 
Closes #483 
- Skip checks for build location and postbuild copy for Versioning_Toolkit
- Do not apply the CodeCompliance checks applicable for the _Enigne and _oM project to _Test solutions, such as null-handling and serialisation. Opted to keep a couple of checks in, such as checking for input/output attributes as those where only warnings, and not errors, and actually would be good to have in place.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Test_Toolkit/%23484-RuleOutVerificationSolutionsAndVersioningToolkitFromIrrelevantChecks?csf=1&web=1&e=4dfX67
> Rule out verification solutions and versioning toolkit from irrelevant checks

- CodeComplianceTest_Engine/Query/Checks/IsExtensionMethod.cs
Closes #488 
Adds a check for '<' in the regex to make sure the split is not going to throw an exception.
See issue for full description.
[CodeComplianceTest.zip](https://github.com/user-attachments/files/17921720/CodeComplianceTest.zip)
Make sure to have the DataViz_Toolkit cloned on its current PR (branch `DataViz_Toolkit-#61-TemplateViews`)
I did the minimum amount of change to avoid disruption but I was wondering if the fact that the regex doesn't limit to the start of the string couldn't create problem. So far, it has worked on all our code so maybe a question to investigate later ?
> Fix bug for Modify methods on an object that contains 'List' in its type

- CodeComplianceTest_Engine/Query/Checks/InputAttributesAreInOrder.cs
Closes #497
Fixes issue where inputs in order where treated as an error, unnecessarily blocking PRs from merge. Check still useful, but should be a warning.
> Reduce status from error to warning for attributes in order check

- CodeComplianceTest_Engine/Compute/CheckProjectFile.cs
Closes #499
Pretty straightforward. Some of our newer projects are using .NET 8 and are failing compliance checks on PRs.
> Allow newer versions of .NET in project compliance check

- CodeComplianceTest_Engine/Query/Checks/HasUniqueMultiOutputAttributes.cs
- CodeComplianceTest_Engine/Query/Checks/HasValidMultiOutputAttributes.cs
- CodeComplianceTest_Engine/Query/Checks/IsValidCreateMethod.cs
Closes #505 
Closes #506 
Closes #507 
- Fix issue with 2darrays for MultiOutputChecks
- Fix issue with Generic return in create methods
- simplify code for IsValidCreateMethod
> Tweaks to compliance checks to handle edge cases

- CodeComplianceTest_Engine/Query/Checks/HasDescriptionAttribute.cs
- CodeComplianceTest_Engine/Query/Checks/IsPublicProperty.cs
- CodeComplianceTest_Engine/Query/Checks/IsVirtualProperty.cs
- CodeComplianceTest_Engine/Query/Checks/MethodNameContainsFileName.cs
- CodeComplianceTest_Engine/Query/Checks/ObjectNameMatchesFileName.cs
- CodeComplianceTest_Engine/Query/Checks/PropertyAccessorsHaveNoBody.cs
Closes #509 
Fixes issue with stacked path arguments introduced in 
https://github.com/BHoM/Test_Toolkit/pull/438 (adding _Tests causing those methods not generally being run)
#456 (Making it so that only create methods are checked for method name contains filename)
Suggesting we do not merge this until after the coming beta release, as it might mean significantly more compliance failures. For the checks actually run after putting this back on. Just looking at the BHoM_Engine this will give an additional 245 files failing, mostly due to missing Description attributes.
> Correct the path arguments to correctly filter as intended

- CodeComplianceTest_Engine/Query/Checks/MethodNameContainsFileName.cs
Closes #522
Fixes issue with Test files being flagged as incompliant when file name does nto match method names.
Test projects are not an Engine and should not live under the same rigid compliance rules as the general Engine does, hence turning it off for them.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Test_Toolkit/%235XX-TurnOffCodeMethodNameCOmplianceForTests?csf=1&web=1&e=762WcR
> Make Test files no longer required to be matching file name to method name

- .ci/unit-tests/Test_Engine_Tests/Compute/DummyObjects.cs
- Test_Engine/Compute/DummyObject.cs
Closes #525
Temporarily turns off dummy bitmaps introduced in #521 to make serialisation checks passed.
To be properly investigated and turned back on in #526
> Turn off dummy bitmap
